version: '3'

services:
  fastapi:
    build: fastapi/
    ports: 
      - 8000:8000
    platform: linux/amd64
    volumes:
      - ./fastapi:/fastapi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  streamlit:
    build: streamlit/
    depends_on:
      fastapi:
        condition: service_healthy
    ports: 
        - 8501:8501
    volumes:
      - ./streamlit:/streamlit
